acl lan-ip user-ip 192.168.0.0/16 10.0.0.0/8 127.0.0.0/8 172.16.0.0/12
require-auth !lan-ip

acl connect method CONNECT
ssl-bump connect

acl maps url google.com/maps google.com/images  fonts.gstatic.com maps.gstatic.com
allow maps

acl everyone user-ip 0.0.0.0/0 ::/0
block everyone


